- name: Variable on Play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
# Note: If we declare a varibale in PLAY level then all the tasks can access that variable.

- name: Variables from File in Play Level
  hosts: all
  vars_files:
   - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}



