- name: Copy prometheus configuration
  template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Copy Alerts configuration
  template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml

- name: Restart Prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
